require:
  - 'rubocop-rails'

AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'test/**/*'

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: true
  Max: 250

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - homolog
    - test
    - development

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Lint/MissingSuper:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
