version: "3.9"

services:
  db:
    image: postgres
    container_name: billing-api-postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - billing-api-volume:/var/lib/postgresql/data:Z
    networks:
      - billing-api-network

  rails:
    build: .
    container_name: billing-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/billing-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - billing-api-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

networks:
  billing-api-network:
    driver: bridge

volumes:
  billing-api-volume:
    external: true
